project_name: credit-bureau-sandbox-aws
random_seed: 42

data:
  source: data/bureau_sample.csv
  id_column: customer_id
  target: defaulted
  datetime: snapshot_date
  train_start: "2022-01-01"
  train_end: "2024-06-30"
  valid_start: "2024-07-01"
  valid_end: "2024-12-31"

features:
  drop: [ ]
  categorical: [ state, employment_status, risk_segment ]
  numeric: [ income, utilization_rate, num_trades, delinq_12m, inquiries_6m, dti, cltv ]
  passthrough: [ age, tenure_months ]

modeling:
  algorithms: [ "logistic_regression", "xgboost", "lightgbm" ]
  class_weight: balanced
  eval_metrics: [ "auc", "ks", "psi" ]
  calibration: true

paths:
  models: outputs/models
  metrics: outputs/metrics
  reports: outputs/reports

governance:
  policy_map: governance/policy_map.yaml
  audit_schema: docs/audit_log_schema.json
